apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: cd-pipeline
spec:
  params:
    - name: repo-url
      type: string
    - name: branch
      type: string
      default: main
    - name: app-name
      type: string
      default: accounts
  workspaces:
    - name: pipeline-workspace
  tasks:
    - name: clone
      taskRef:
        name: git-clone
      workspaces:
        - name: output
          workspace: pipeline-workspace
      params:
        - name: url
          value: $(params.repo-url)
        - name: revision
          value: $(params.branch)
    
    - name: lint
      taskRef:
        name: flake8
      runAfter:
        - clone
      workspaces:
        - name: source
          workspace: pipeline-workspace
    
    - name: tests
      taskRef:
        name: nose
      runAfter:
        - clone
      workspaces:
        - name: source
          workspace: pipeline-workspace
    
    - name: deploy
      runAfter:
        - lint
        - tests
      workspaces:
        - name: source
          workspace: pipeline-workspace
      taskSpec:
        workspaces:
          - name: source
        steps:
          - name: deploy
            image: quay.io/openshift/origin-cli:latest
            script: |
              #!/bin/sh
              oc apply -f deploy/
              oc rollout restart deployment/accounts
              oc rollout status deployment/accounts
